name: test-and-deploy-workflow
run-name: ${{ github.actor }} push a new change 🚀
on: 
    push:
        branches: [master]
jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
        -   name: install repository js
            uses: actions/checkout@v3
        -   name: install node js
            uses: actions/setup-node@v3
            with: 
                node-version:
        -   name: install dependencies
            run: npm ci
